"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BarChart3, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, Home, Info, Plus, Share2, ShoppingCart, SlidersHorizontal, WalletCards } from "lucide-react";
import { ApiError, api, type BudgetCategory, type BudgetMonth } from "@mykhaya/api-client";
import { AppShellContent } from "@/components/app-shell";
import { useActiveHome } from "@/components/use-active-home";

export type BudgetScreen = "overview" | "categories" | "category-detail" | "income" | "edit-plan" | "spending" | "entry" | "entry-edit" | "settings" | "sharing" | "together";

const money = (value: number, currency = "GBP") => new Intl.NumberFormat("en-GB", { style: "currency", currency, maximumFractionDigits: 2 }).format(value);
const monthLabel = (year: number, month: number) => new Intl.DateTimeFormat("en-GB", { month: "long", year: "numeric" }).format(new Date(year, month - 1, 1));
const currentPeriod = () => { const now = new Date(); return { year: now.getFullYear(), month: now.getMonth() + 1 }; };

function BudgetArtwork() { return <div className="budget-artwork" aria-hidden="true"><img src="/images/PiggyBank_Budget_Image.png" alt="" /></div>; }

function BudgetTabs({ active }: { active: "overview" | "categories" | "income" | "settings" }) {
  return <nav className="budget-tabs" aria-label="Budget sections">
    <Link className={active === "overview" ? "active" : ""} href="/budget">Overview</Link>
    <Link className={active === "categories" ? "active" : ""} href="/budget/categories">Categories</Link>
    <Link className={active === "income" ? "active" : ""} href="/budget/income">Income</Link>
    <Link className={active === "settings" ? "active" : ""} href="/budget/settings">Settings</Link>
  </nav>;
}

function PeriodControl({ year, month, onChange }: { year: number; month: number; onChange: (year: number, month: number) => void }) {
  const move = (delta: number) => { const next = new Date(year, month - 1 + delta, 1); onChange(next.getFullYear(), next.getMonth() + 1); };
  return <div className="budget-period-control"><button type="button" aria-label="Previous month" onClick={() => move(-1)}><ChevronLeft size={22} /></button><strong>{monthLabel(year, month)}</strong><ChevronDown size={18} aria-hidden="true" /><button type="button" aria-label="Next month" onClick={() => move(1)}><ChevronRight size={22} /></button></div>;
}

function BudgetHero({ title, description, activeTab, showTabs = true }: { title: string; description: string; activeTab?: "overview" | "categories" | "income" | "settings"; showTabs?: boolean }) {
  return <><div className="budget-breadcrumb"><Link href="/settings"><ArrowLeft size={19} /> More</Link></div><section className="budget-hero"><div><p className="budget-eyebrow">Budget</p><h1>{title}</h1><p>{description}</p></div><BudgetArtwork /></section>{showTabs && activeTab && <BudgetTabs active={activeTab} />}</>;
}

function LoadingState() { return <main className="standard-page module-page budget-page"><p role="status">Loading Budget…</p></main>; }
function UnavailableState() { return <main className="standard-page module-page budget-page"><div className="budget-empty-state"><p className="budget-eyebrow">Budget</p><h1>Budget isn’t available here</h1><p>This Home has not enabled Budget. Ask a Home Admin to enable it before opening this page.</p><Link className="secondary" href="/settings">Back to More</Link></div></main>; }
function MonthUnavailable({ onCreate }: { onCreate: () => void }) { return <div className="budget-empty-state budget-empty-state-compact"><CalendarDays size={28} aria-hidden="true" /><h2>No plan for this month yet</h2><p>Create this month’s snapshot to start planning. Older months remain independent.</p><button type="button" onClick={onCreate}>Create month</button></div>; }
function EntryEditUnavailable() { return null; }
function StatCard({ label, value, icon: Icon }: { label: string; value: string; icon: typeof WalletCards }) { return <div className="budget-stat-card"><span className="budget-icon"><Icon size={23} /></span><span><small>{label}</small><strong>{value}</strong></span></div>; }

function CategoryRow({ category, month, href }: { category: BudgetCategory; month?: BudgetMonth; href: string }) {
  const snapshot = month?.categories.find((item) => item.category_id === category.id);
  return <Link className="budget-list-row" href={href}><span className="budget-icon"><Home size={23} /></span><span className="budget-row-copy"><strong>{snapshot?.category_name ?? category.name}</strong><small>{snapshot ? `Planned ${money(snapshot.planned_amount)} · Actual ${money(snapshot.actual_amount)} · Remaining ${money(Math.max(snapshot.planned_amount - snapshot.actual_amount, 0))}` : "No plan for this month"}</small></span><ChevronRight size={22} aria-hidden="true" /></Link>;
}

function useBudgetAccess(homeId: string | null) {
  const [ready, setReady] = useState(false); const [available, setAvailable] = useState(false);
  useEffect(() => { setReady(false); setAvailable(false); if (!homeId) return; let cancelled = false; api.budgetProfile(homeId).then(() => { if (!cancelled) { setAvailable(true); setReady(true); } }).catch(() => { if (!cancelled) { setAvailable(false); setReady(true); } }); return () => { cancelled = true; }; }, [homeId]);
  return { ready, available };
}

function useBudgetMonth(homeId: string | null, year: number, month: number) {
  const [monthData, setMonthData] = useState<BudgetMonth | null>(null); const [loading, setLoading] = useState(true); const [missing, setMissing] = useState(false);
  const reload = useCallback(() => { if (!homeId) return; setLoading(true); setMissing(false); api.budgetMonth(homeId, year, month).then(setMonthData).catch((cause) => { if (cause instanceof ApiError && cause.status === 404) setMissing(true); else setMonthData(null); }).finally(() => setLoading(false)); }, [homeId, month, year]);
  useEffect(() => { setMonthData(null); reload(); }, [reload]);
  return { monthData, loading, missing, reload };
}

function Overview({ homeId, currency }: { homeId: string; currency: string }) {
  const [period, setPeriod] = useState(currentPeriod()); const { monthData, loading, missing, reload } = useBudgetMonth(homeId, period.year, period.month); const [categories, setCategories] = useState<BudgetCategory[]>([]);
  useEffect(() => { api.budgetCategories(homeId).then(setCategories).catch(() => setCategories([])); }, [homeId]);
  const planned = monthData?.categories.reduce((sum, item) => sum + item.planned_amount, 0) ?? 0; const actual = monthData?.categories.reduce((sum, item) => sum + item.actual_amount, 0) ?? 0;
  return <><BudgetHero title="Budget" description="Plan where your money goes." activeTab="overview" /><PeriodControl {...period} onChange={(year, month) => setPeriod({ year, month })} />{loading ? <p role="status">Loading this month…</p> : missing ? <MonthUnavailable onCreate={() => api.createBudgetMonth(homeId, period.year, period.month).then(reload)} /> : <><section className="budget-stat-grid"><StatCard label="Planned" value={money(planned, currency)} icon={WalletCards} /><StatCard label="Actual" value={money(actual, currency)} icon={BarChart3} /><StatCard label="Remaining" value={money(Math.max(planned - actual, 0), currency)} icon={CircleDollarSign} /></section><div className="budget-section-heading"><h2>Categories</h2><Link href="/budget/categories">View all</Link></div><div className="budget-list">{categories.map((category) => <CategoryRow key={category.id} category={category} month={monthData ?? undefined} href={`/budget/categories/${category.id}`} />)}</div>{!categories.length && <p className="budget-note">Add your first category to start your plan.</p>}</>}</>;
}

function Categories({ homeId }: { homeId: string }) {
  const [categories, setCategories] = useState<BudgetCategory[]>([]); const [name, setName] = useState(""); const [error, setError] = useState(""); const load = useCallback(() => { api.budgetCategories(homeId).then(setCategories).catch(() => setCategories([])); }, [homeId]); useEffect(() => { load(); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; setError(""); try { await api.createBudgetCategory(homeId, { name: name.trim() }); setName(""); load(); } catch { setError("That category could not be added."); } }
  return <><BudgetHero title="Categories" description="Track where your budget goes." activeTab="categories" /><div className="budget-list">{categories.map((category) => <CategoryRow key={category.id} category={category} href={`/budget/categories/${category.id}`} />)}</div><form className="budget-inline-form" onSubmit={submit}><label htmlFor="budget-category">Add category</label><div><input id="budget-category" value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Housing" maxLength={100} /><button type="submit"><Plus size={18} /> Add</button></div>{error && <p role="alert">{error}</p>}</form></>;
}

function CategoryDetail({ homeId, categoryId }: { homeId: string; categoryId: string }) {
  const period = currentPeriod(); const { monthData, loading, missing, reload } = useBudgetMonth(homeId, period.year, period.month); const [categories, setCategories] = useState<BudgetCategory[]>([]); const [planned, setPlanned] = useState(""); const [source, setSource] = useState<"manual" | "entries">("manual"); const [actual, setActual] = useState("");
  useEffect(() => { api.budgetCategories(homeId).then(setCategories).catch(() => undefined); }, [homeId]); const category = categories.find((item) => item.id === categoryId); const snapshot = monthData?.categories.find((item) => item.category_id === categoryId); useEffect(() => { if (snapshot) { setPlanned(String(snapshot.planned_amount)); setSource(snapshot.actual_source); setActual(snapshot.manual_actual == null ? "" : String(snapshot.manual_actual)); } }, [snapshot]);
  async function savePlan(event: FormEvent) { event.preventDefault(); if (snapshot) { await api.updateBudgetPlan(homeId, period.year, period.month, categoryId, Number(planned)); reload(); } } async function saveActual(event: FormEvent) { event.preventDefault(); if (snapshot) { await api.updateBudgetActual(homeId, period.year, period.month, categoryId, source === "manual" ? { source, manual_actual: Number(actual) } : { source }); reload(); } }
  return <><BudgetHero title={category?.name ?? "Category"} description="Optional spending detail sits under your plan." showTabs={false} /><div className="budget-back-link"><Link href="/budget/categories"><ArrowLeft size={18} /> Categories</Link></div>{loading ? <p role="status">Loading this month…</p> : missing ? <MonthUnavailable onCreate={() => api.createBudgetMonth(homeId, period.year, period.month).then(reload)} /> : !snapshot ? <p className="budget-note">This category is not part of the selected month snapshot.</p> : <><section className="budget-stat-grid"><StatCard label="Planned" value={money(snapshot.planned_amount)} icon={CircleDollarSign} /><StatCard label="Actual" value={money(snapshot.actual_amount)} icon={BarChart3} /><StatCard label="Remaining" value={money(Math.max(snapshot.planned_amount - snapshot.actual_amount, 0))} icon={CircleDollarSign} /></section><form className="budget-form-card" onSubmit={savePlan}><h2>Plan amount</h2><label htmlFor="planned-amount">Planned per month</label><input id="planned-amount" type="number" min="0" step="0.01" value={planned} onChange={(event) => setPlanned(event.target.value)} /><button type="submit">Save plan</button></form><form className="budget-form-card" onSubmit={saveActual}><h2>Actual amount</h2><label htmlFor="actual-source">Actual source</label><select id="actual-source" value={source} onChange={(event) => setSource(event.target.value as "manual" | "entries")}><option value="manual">Manual amount</option><option value="entries">Spending entries</option></select>{source === "manual" && <><label htmlFor="manual-actual">Actual this month</label><input id="manual-actual" type="number" min="0" step="0.01" value={actual} onChange={(event) => setActual(event.target.value)} /></>}<button type="submit">Save actual</button></form><Link className="budget-action-row" href={`/budget/spending/new?category=${categoryId}`}><span className="budget-icon"><ShoppingCart size={21} /></span><strong>Add spending entry</strong><ArrowRight size={19} /></Link></>}</>;
}

function Income({ homeId, currency }: { homeId: string; currency: string }) { const [sources, setSources] = useState<{ id: string; name: string; sort_order: number; archived: boolean }[]>([]); const [name, setName] = useState(""); const load = useCallback(() => { api.budgetIncomeSources(homeId).then(setSources).catch(() => setSources([])); }, [homeId]); useEffect(() => { load(); }, [load]); async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; await api.createBudgetIncomeSource(homeId, { name: name.trim() }); setName(""); load(); } return <><BudgetHero title="Income" description="Plan what comes in each month." activeTab="income" /><section className="budget-stat-grid"><StatCard label="Expected income" value={money(0, currency)} icon={WalletCards} /><StatCard label="Received" value={money(0, currency)} icon={CalendarDays} /></section><h2 className="budget-section-title">Income sources</h2><div className="budget-list">{sources.map((source) => <div className="budget-list-row" key={source.id}><span className="budget-icon"><WalletCards size={22} /></span><span className="budget-row-copy"><strong>{source.name}</strong><small>Set this month’s expected and received amount</small></span><ChevronRight size={20} /></div>)}</div><form className="budget-inline-form" onSubmit={submit}><label htmlFor="budget-income-source">Add income source</label><div><input id="budget-income-source" value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Salary" maxLength={100} /><button type="submit"><Plus size={18} /> Add</button></div></form></>; }

function EditPlan({ homeId }: { homeId: string }) { const period = currentPeriod(); const { monthData, loading, missing, reload } = useBudgetMonth(homeId, period.year, period.month); const [values, setValues] = useState<Record<string, string>>({}); useEffect(() => { if (monthData) setValues(Object.fromEntries(monthData.categories.map((item) => [item.category_id, String(item.planned_amount)]))); }, [monthData]); async function save() { if (monthData) { await Promise.all(monthData.categories.map((item) => api.updateBudgetPlan(homeId, period.year, period.month, item.category_id, Number(values[item.category_id] ?? 0)))); reload(); } } return <><BudgetHero title="Edit plan" description="Adjust your monthly budget." showTabs={false} /><PeriodControl {...period} onChange={() => undefined} />{loading ? <p role="status">Loading this month…</p> : missing ? <MonthUnavailable onCreate={() => api.createBudgetMonth(homeId, period.year, period.month).then(reload)} /> : <><h2 className="budget-section-title">Plan categories</h2><div className="budget-plan-list">{monthData?.categories.map((item) => <label className="budget-plan-row" key={item.category_id}><span className="budget-icon"><Home size={21} /></span><strong>{item.category_name}</strong><input aria-label={`${item.category_name} planned amount`} type="number" min="0" step="0.01" value={values[item.category_id] ?? ""} onChange={(event) => setValues((current) => ({ ...current, [item.category_id]: event.target.value }))} /></label>)}</div><button type="button" onClick={save}>Save plan</button></>}</>; }

function EntryForm({ homeId, categoryId }: { homeId: string; categoryId?: string }) { const [categories, setCategories] = useState<BudgetCategory[]>([]); const [category, setCategory] = useState(categoryId ?? ""); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [spentOn, setSpentOn] = useState(new Date().toISOString().slice(0, 10)); const [message, setMessage] = useState(""); useEffect(() => { api.budgetCategories(homeId).then((rows) => { setCategories(rows); if (!categoryId && rows[0]) setCategory(rows[0].id); }).catch(() => setCategories([])); }, [categoryId, homeId]); async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); await api.createBudgetEntry(homeId, { category_id: category, description, amount: Number(amount), spent_on: spentOn }); setMessage("Spending entry added."); setDescription(""); setAmount(""); } return <form className="budget-form-card" onSubmit={submit}><label htmlFor="entry-category">Category</label><select id="entry-category" value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label htmlFor="entry-description">Description</label><input id="entry-description" value={description} onChange={(event) => setDescription(event.target.value)} required placeholder="e.g. Groceries" /><label htmlFor="entry-amount">Amount</label><input id="entry-amount" type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} required /><label htmlFor="entry-date">Date</label><input id="entry-date" type="date" value={spentOn} onChange={(event) => setSpentOn(event.target.value)} required /><button type="submit">Add entry</button>{message && <p role="status">{message}</p>}</form>; }

function Spending({ homeId }: { homeId: string }) { return <><BudgetHero title="Spending entries" description="Optional detail under your budget." showTabs={false} /><div className="budget-search-row"><label className="sr-only" htmlFor="spending-search">Search spending entries</label><input id="spending-search" placeholder="Search spending entries…" /><button type="button" aria-label="Filter spending entries"><SlidersHorizontal size={20} /></button></div><div className="budget-note"><Info size={20} /><span>Use Add entry to record optional spending detail for this Budget.</span></div><h2 className="budget-section-title">Add an entry</h2><EntryForm homeId={homeId} /></>; }
function SettingsScreen({ currency }: { currency: string }) { return <><BudgetHero title="Settings" description="Manage how Budget works for you." activeTab="settings" /><div className="budget-list"><div className="budget-list-row"><span className="budget-icon"><CircleDollarSign size={22} /></span><span className="budget-row-copy"><strong>Currency</strong><small>{currency}</small></span><ChevronRight size={20} /></div><div className="budget-list-row"><span className="budget-icon"><CalendarDays size={22} /></span><span className="budget-row-copy"><strong>Month starts on</strong><small>1st of the month</small></span><ChevronRight size={20} /></div><Link className="budget-list-row" href="/budget/sharing"><span className="budget-icon"><Share2 size={22} /></span><span className="budget-row-copy"><strong>Partner sharing</strong><small>Choose what your partner can see</small></span><ChevronRight size={20} /></Link></div><div className="budget-note"><Info size={20} /><span>Sharing is always optional. Nothing is shared automatically.</span></div></>; }
function Sharing({ homeId }: { homeId: string }) { const [members, setMembers] = useState<{ user_id: string; display_name: string; relationship: string }[]>([]); const [shares, setShares] = useState<{ id: string; partner_user_id: string; level: "summary" | "categories" | "full"; active: boolean }[]>([]); const load = useCallback(() => { Promise.all([api.members(homeId), api.budgetShares(homeId)]).then(([nextMembers, nextShares]) => { setMembers(nextMembers.filter((member) => member.relationship !== "child")); setShares(nextShares); }).catch(() => undefined); }, [homeId]); useEffect(() => { load(); }, [load]); async function setLevel(userId: string, level: "summary" | "categories" | "full") { await api.setBudgetShare(homeId, userId, level); load(); } async function revoke(userId: string) { await api.revokeBudgetShare(homeId, userId); load(); } return <><BudgetHero title="Partner sharing" description="Choose what your partner can see." showTabs={false} /><div className="budget-share-intro"><Share2 size={25} /><div><strong>Sharing is optional</strong><p>Your Budget remains private until you choose a person and a sharing level.</p></div></div><h2 className="budget-section-title">Sharing level</h2><div className="budget-share-list">{members.map((member) => { const share = shares.find((item) => item.partner_user_id === member.user_id && item.active); return <div className="budget-share-card" key={member.user_id}><div><strong>{member.display_name}</strong><small>{share ? "Sharing enabled" : "Private"}</small></div>{share ? <><select aria-label={`Sharing level for ${member.display_name}`} value={share.level} onChange={(event) => setLevel(member.user_id, event.target.value as "summary" | "categories" | "full")}><option value="summary">Summary only</option><option value="categories">Shared categories</option><option value="full">Full budget</option></select><button type="button" className="tertiary" onClick={() => revoke(member.user_id)}>Revoke</button></> : <button type="button" onClick={() => setLevel(member.user_id, "summary")}>Share</button>}</div>; })}</div><Link className="budget-action-row" href="/budget/together"><span className="budget-icon"><Share2 size={21} /></span><strong>View Together</strong><ArrowRight size={19} /></Link></>; }
function Together() { return <><BudgetHero title="Together" description="See the budget you have chosen to share." showTabs={false} /><div className="budget-empty-state"><Share2 size={30} aria-hidden="true" /><h2>No shared Budget yet</h2><p>When someone shares their Budget with you, the Personal/Together selector and shared summary will appear here.</p><Link className="secondary" href="/budget/settings">Back to Budget settings</Link></div></>; }

export function BudgetModule({ screen, categoryId, entryCategoryId }: { screen: BudgetScreen; categoryId?: string; entryCategoryId?: string }) {
  const { activeHomeId } = useActiveHome(); const { ready, available } = useBudgetAccess(activeHomeId); const [currency, setCurrency] = useState("GBP"); useEffect(() => { if (activeHomeId) api.budgetProfile(activeHomeId).then((profile) => setCurrency(profile.currency)).catch(() => undefined); }, [activeHomeId]);
  if (!ready || !activeHomeId) return <AppShellContent><LoadingState /></AppShellContent>; if (!available) return <AppShellContent><UnavailableState /></AppShellContent>;
  let content: React.ReactNode; if (screen === "overview") content = <Overview homeId={activeHomeId} currency={currency} />; else if (screen === "categories") content = <Categories homeId={activeHomeId} />; else if (screen === "category-detail") content = <CategoryDetail homeId={activeHomeId} categoryId={categoryId ?? ""} />; else if (screen === "income") content = <Income homeId={activeHomeId} currency={currency} />; else if (screen === "edit-plan") content = <EditPlan homeId={activeHomeId} />; else if (screen === "spending") content = <Spending homeId={activeHomeId} />; else if (screen === "entry") content = <><BudgetHero title="Add spending entry" description="Keep optional detail under your budget." showTabs={false} /><div className="budget-back-link"><Link href="/budget/spending"><ArrowLeft size={18} /> Spending entries</Link></div><EntryForm homeId={activeHomeId} categoryId={entryCategoryId} /></>; else if (screen === "entry-edit") content = <><BudgetHero title="Edit spending entry" description="Update optional detail under your budget." showTabs={false} /><div className="budget-back-link"><Link href="/budget/spending"><ArrowLeft size={18} /> Spending entries</Link></div><EntryEditUnavailable /></>; else if (screen === "settings") content = <SettingsScreen currency={currency} />; else if (screen === "sharing") content = <Sharing homeId={activeHomeId} />; else content = <Together />;
  return <AppShellContent><main className="standard-page module-page budget-page">{content}</main></AppShellContent>;
}
