"use client";

import { FormEvent, useEffect, useState } from "react";
import { ApiError, platformApi } from "@mykhaya/api-client";
import { PlatformShell } from "@/components/platform-shell";
import { CcPage } from "@/components/control-centre/page-shell";
import { CcPageHeader } from "@/components/control-centre/page-header";
import { CcLegalSubnav } from "@/components/control-centre/legal-subnav";
import { CcNotice } from "@/components/control-centre/status-message";
import { CcBadge } from "@/components/control-centre/badge";

type RequestRow = { id: string; reference: string; user_id: string | null; user_display_name: string | null; user_email: string | null; request_type: string; received_at: string; identity_status: string; due_date: string; status: string; internal_notes: string | null; overdue: boolean };
const typeLabels: Record<string, string> = { subject_access: "Subject Access Request", rectification: "Rectification", erasure: "Erasure", restriction: "Restriction", objection: "Objection", data_portability: "Data portability", other: "Other" };
const statuses = ["received", "identity_check", "in_progress", "awaiting_user", "completed", "declined"];
function formText(form: FormData, name: string) { const value = form.get(name); return typeof value === "string" ? value : ""; }
function dueTone(row: RequestRow) { return row.overdue ? "danger" : row.status === "completed" || row.status === "declined" ? "neutral" : "warning"; }

export default function PrivacyRequestsPage() {
  const [rows, setRows] = useState<RequestRow[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [formOpen, setFormOpen] = useState(false);
  async function load() { try { setRows(await platformApi.get<RequestRow[]>("/compliance/privacy-requests")); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to load privacy requests."); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await platformApi.post("/compliance/privacy-requests", { user_id: formText(form, "user_id") || null, request_type: formText(form, "request_type"), due_date: formText(form, "due_date"), internal_notes: formText(form, "internal_notes") || null, reason: formText(form, "reason"), confirmed: true }); setMessage("Privacy request created."); setError(""); setFormOpen(false); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to create privacy request."); } }
  async function update(row: RequestRow, changes: Record<string, string>) { const reason = window.prompt("Reason for this privacy-request change (at least 10 characters):", "Processing update recorded by PCC"); if (!reason) return; try { await platformApi.patch(`/compliance/privacy-requests/${row.id}`, { ...changes, reason, confirmed: true }); setMessage(`${row.reference} updated.`); setError(""); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Unable to update privacy request."); } }
  return <PlatformShell><CcPage wide className="cc-privacy-requests"><CcPageHeader eyebrow="Legal & Compliance" title="Privacy Requests" description="Track data-rights requests, deadlines and internal handling evidence. Notes are restricted to PCC operators." primaryAction={<button className="cc-action cc-action-primary" onClick={() => setFormOpen((value) => !value)}>New request</button>} /><CcLegalSubnav />{message && <CcNotice tone="success">{message}</CcNotice>}{error && <CcNotice tone="error">{error}</CcNotice>}{formOpen && <form className="cc-compliance-form" onSubmit={create}><label>User ID (optional)<input name="user_id" placeholder="Known MyKhaya user UUID" /></label><label>Request type<select name="request_type" defaultValue="subject_access">{Object.entries(typeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Statutory due date<input name="due_date" type="date" required defaultValue={new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10)} /></label><label>Internal notes<textarea name="internal_notes" maxLength={10000} /></label><label>Reason for creation<input name="reason" required minLength={10} defaultValue="Privacy request received and logged" /></label><button className="cc-action cc-action-primary">Create request</button></form>}<div className="cc-legal-table-wrap"><table className="cc-legal-table"><caption className="sr-only">Privacy requests</caption><thead><tr><th>Reference</th><th>Requester</th><th>Type</th><th>Identity</th><th>Due</th><th>Status</th><th>Internal notes</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.reference}</strong></td><td>{row.user_display_name ?? "Unknown user"}<small>{row.user_email ?? row.user_id ?? "No linked account"}</small></td><td>{typeLabels[row.request_type] ?? row.request_type}</td><td><select aria-label={`Identity for ${row.reference}`} value={row.identity_status} onChange={(event) => void update(row, { identity_status: event.target.value })}><option value="pending">Pending</option><option value="verified">Verified</option><option value="failed">Failed</option></select></td><td><CcBadge tone={dueTone(row)}>{row.overdue ? "Overdue · " : ""}{row.due_date}</CcBadge></td><td><select aria-label={`Status for ${row.reference}`} value={row.status} onChange={(event) => void update(row, { status: event.target.value })}>{statuses.map((value) => <option value={value} key={value}>{value.replaceAll("_", " ")}</option>)}</select></td><td>{row.internal_notes ?? "—"}</td></tr>)}</tbody></table>{!rows.length && <p className="cc-user-profile-empty">No privacy requests recorded.</p>}</div></CcPage></PlatformShell>;
}
